# Generated by Django 3.0.3 on 2022-01-07 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_start', models.IntegerField(blank=True, null=True)),
                ('domain_end', models.IntegerField(blank=True, null=True)),
                ('domain_description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism_id', models.IntegerField(blank=True, null=True)),
                ('organism_genus', models.CharField(blank=True, max_length=256, null=True)),
                ('organism_sp', models.CharField(blank=True, max_length=256, null=True)),
                ('organism_clade', models.CharField(blank=True, default='E', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfam_id', models.CharField(blank=True, max_length=25, null=True)),
                ('pfam_description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(blank=True, max_length=256, null=True)),
                ('protein_sequence', models.CharField(blank=True, max_length=256, null=True)),
                ('protein_length', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinDomainLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteinapp.Domain')),
                ('protein_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteinapp.Protein')),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='domain',
            field=models.ManyToManyField(through='proteinapp.ProteinDomainLink', to='proteinapp.Domain'),
        ),
        migrations.AddField(
            model_name='protein',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteinapp.Organism'),
        ),
        migrations.AddField(
            model_name='domain',
            name='domain_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='proteinapp.Pfam'),
        ),
    ]
